# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 06:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=15, null=True, unique=True, verbose_name='\u8bc4\u8bba')),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=20, verbose_name='\u5546\u54c1\u7f16\u53f7')),
                ('name', models.CharField(max_length=200, verbose_name='\u5546\u54c1\u540d')),
                ('price', models.CharField(max_length=20, verbose_name='\u5f53\u524d\u4ef7')),
                ('crawl_time', models.CharField(max_length=20, verbose_name='\u6293\u53d6\u65f6\u95f4')),
                ('ch_price', models.CharField(max_length=10, verbose_name='\u4ef7\u683c\u53d8\u5316')),
                ('image_url', models.CharField(max_length=500, verbose_name='\u56fe\u7247')),
                ('url', models.CharField(max_length=500, verbose_name='\u5546\u54c1\u7f51\u5740')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_user', to=settings.AUTH_USER_MODEL, verbose_name='\u8d27\u4e3b')),
            ],
        ),
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=5000, null=True)),
                ('cycle', models.CharField(choices=[(1800, '\u534a\u5c0f\u65f6'), (3600, '\u4e00\u5c0f\u65f6'), (7200, '\u4e24\u5c0f\u65f6'), (18000, '\u4e94\u5c0f\u65f6'), (86400, '\u4e00\u5929'), (172800, '\u4e24\u5929'), (518400, '\u4e00\u5468')], default=86400, max_length=50, verbose_name='\u6293\u53d6\u95f4\u9694\u65f6\u95f4')),
                ('start_time', models.CharField(max_length=20, null=True, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pa_spider', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe4\xb8\xaa\xe4\xba\xba\xe7\x88\xac\xe8\x99\xab')),
            ],
        ),
        migrations.CreateModel(
            name='Updata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=20, verbose_name='\u5546\u54c1\u7f16\u53f7')),
                ('price', models.CharField(max_length=20, verbose_name='\u5f53\u524d\u4ef7')),
                ('last_price', models.CharField(max_length=20, verbose_name='\u539f\u4ef7')),
                ('crawl_time', models.CharField(max_length=50, verbose_name='\u6293\u53d6\u65f6\u95f4')),
            ],
        ),
    ]
