# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='image_url',
            field=models.CharField(max_length=500, verbose_name='\u56fe\u7247'),
        ),
    ]
