# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spider',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='\u90ae\u4ef6\u5730\u5740'),
        ),
    ]
