# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160229_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spider',
            name='status',
        ),
        migrations.AddField(
            model_name='spider',
            name='start_time',
            field=models.CharField(max_length=20, null=True, verbose_name='\u5f00\u59cb\u65f6\u95f4'),
        ),
    ]
