# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160303_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spider',
            name='start_time',
        ),
        migrations.AddField(
            model_name='spider',
            name='status',
            field=models.CharField(default=b'run', max_length=10, verbose_name='\u72b6\u6001'),
        ),
    ]
